//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.OpenApi.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SRResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.OpenApi.Properties.SRResource", typeof(SRResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There must be an active scope for name &apos;{0}&apos; to be written..
        /// </summary>
        internal static string ActiveScopeNeededForPropertyNameWriting {
            get {
                return ResourceManager.GetString("ActiveScopeNeededForPropertyNameWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The argument &apos;{0}&apos; is null, empty or consists only of white-space..
        /// </summary>
        internal static string ArgumentNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The filed name &apos;{0}&apos; of extension doesn&apos;t begin with x-..
        /// </summary>
        internal static string ExtensionFieldNameMustBeginWithXDash {
            get {
                return ResourceManager.GetString("ExtensionFieldNameMustBeginWithXDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indentation level cannot be lower than 0..
        /// </summary>
        internal static string IndentationLevelInvalid {
            get {
                return ResourceManager.GetString("IndentationLevelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The active scope must be an object scope for property name &apos;{0}&apos; to be written..
        /// </summary>
        internal static string ObjectScopeNeededForPropertyNameWriting {
            get {
                return ResourceManager.GetString("ObjectScopeNeededForPropertyNameWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while processing the Open API document..
        /// </summary>
        internal static string OpenApiExceptionGenericError {
            get {
                return ResourceManager.GetString("OpenApiExceptionGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The given OpenAPI format &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string OpenApiFormatNotSupported {
            get {
                return ResourceManager.GetString("OpenApiFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The object element name &apos;{0}&apos; is required..
        /// </summary>
        internal static string OpenApiObjectElementIsRequired {
            get {
                return ResourceManager.GetString("OpenApiObjectElementIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The OpenApi element &apos;{0}&apos; is already marked as reference object..
        /// </summary>
        internal static string OpenApiObjectMarkAsReference {
            get {
                return ResourceManager.GetString("OpenApiObjectMarkAsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the parameter location is &quot;path&quot;, this property is REQUIRED and its value MUST be true.
        /// </summary>
        internal static string OpenApiParameterRequiredPropertyMandatory {
            get {
                return ResourceManager.GetString("OpenApiParameterRequiredPropertyMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The given OpenAPI specification version &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string OpenApiSpecVersionNotSupported {
            get {
                return ResourceManager.GetString("OpenApiSpecVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The type &apos;{0}&apos; is not supported in Open API document..
        /// </summary>
        internal static string OpenApiUnsupportedValueType {
            get {
                return ResourceManager.GetString("OpenApiUnsupportedValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while writing the Open API document..
        /// </summary>
        internal static string OpenApiWriterExceptionGenericError {
            get {
                return ResourceManager.GetString("OpenApiWriterExceptionGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The given primitive type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string PrimitiveTypeNotSupported {
            get {
                return ResourceManager.GetString("PrimitiveTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The reference string &apos;{0}&apos; has invalid format..
        /// </summary>
        internal static string ReferenceHasInvalidFormat {
            get {
                return ResourceManager.GetString("ReferenceHasInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The runtime expression &apos;{0}&apos; has invalid format..
        /// </summary>
        internal static string RuntimeExpressionHasInvalidFormat {
            get {
                return ResourceManager.GetString("RuntimeExpressionHasInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The runtime expression &apos;{0}&apos; should start with &apos;$&apos;.
        /// </summary>
        internal static string RuntimeExpressionMustBeginWithDollar {
            get {
                return ResourceManager.GetString("RuntimeExpressionMustBeginWithDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scope must be present to end..
        /// </summary>
        internal static string ScopeMustBePresentToEnd {
            get {
                return ResourceManager.GetString("ScopeMustBePresentToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The scope to end is expected to be of type &apos;{0}&apos; but it is of type &apos;{0}&apos;..
        /// </summary>
        internal static string ScopeToEndHasIncorrectType {
            get {
                return ResourceManager.GetString("ScopeToEndHasIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source expression &apos;{0}&apos; has invalid format..
        /// </summary>
        internal static string SourceExpressionHasInvalidFormat {
            get {
                return ResourceManager.GetString("SourceExpressionHasInvalidFormat", resourceCulture);
            }
        }
    }
}
